// <auto-generated />
using System;
using System.Collections.Generic;
using KassaEventsDataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KassaEventsDataBase.Migrations
{
    [DbContext(typeof(KassaEventsDbContext))]
    partial class KassaEventsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("KassaEventsDataBase.DbKassaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .HasColumnType("Map(String, String)");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.ToTable("kass_events", (string)null);

                    b
                        .HasAnnotation("ClickHouse:Engine", "MergeTree")
                        .HasAnnotation("ClickHouse:OrderBy", new[] { "Id" })
                        .HasAnnotation("ClickHouse:PrimaryKey", new[] { "id", "timestamp" });
                });
#pragma warning restore 612, 618
        }
    }
}
