// <auto-generated />
using KassaStoreDataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KassaStoreDataBase.Migrations
{
    [DbContext(typeof(KassaStoreDbContext))]
    partial class KassaStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KassaStoreDataBase.DbCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ToRubleRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Рубли",
                            ShortName = "RUB",
                            ToRubleRate = 1m
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Доллары",
                            ShortName = "USD",
                            ToRubleRate = 71.9077m
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Йены",
                            ShortName = "JPY",
                            ToRubleRate = 0.447911m
                        });
                });

            modelBuilder.Entity("KassaStoreDataBase.DbGood", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceRub")
                        .HasColumnType("numeric");

                    b.HasKey("Code");

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Count = 1001,
                            Name = "Тапки",
                            PriceRub = 50m
                        },
                        new
                        {
                            Code = 2,
                            Count = 100,
                            Name = "Вертолёт",
                            PriceRub = 5000000m
                        },
                        new
                        {
                            Code = 3,
                            Count = 1000000,
                            Name = "Шприц",
                            PriceRub = 5m
                        },
                        new
                        {
                            Code = 4,
                            Count = 1001,
                            Name = "Плюмбус",
                            PriceRub = 76m
                        },
                        new
                        {
                            Code = 5,
                            Count = 1001,
                            Name = "Замок",
                            PriceRub = 42000000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
