CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Currencies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ShortName" text NOT NULL,
    "FullName" text NOT NULL,
    "ToRubleRate" numeric NOT NULL,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("Id")
);

CREATE TABLE "Goods" (
    "Code" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "PriceRub" numeric NOT NULL,
    "Count" integer NOT NULL,
    CONSTRAINT "PK_Goods" PRIMARY KEY ("Code")
);

INSERT INTO "Currencies" ("Id", "FullName", "ShortName", "ToRubleRate")
VALUES (1, 'Рубли', 'RUB', 1.0);
INSERT INTO "Currencies" ("Id", "FullName", "ShortName", "ToRubleRate")
VALUES (2, 'Доллары', 'USD', 71.9077);
INSERT INTO "Currencies" ("Id", "FullName", "ShortName", "ToRubleRate")
VALUES (3, 'Йены', 'JPY', 0.447911);

INSERT INTO "Goods" ("Code", "Count", "Name", "PriceRub")
VALUES (1, 1001, 'Тапки', 50.0);
INSERT INTO "Goods" ("Code", "Count", "Name", "PriceRub")
VALUES (2, 100, 'Вертолёт', 5000000.0);
INSERT INTO "Goods" ("Code", "Count", "Name", "PriceRub")
VALUES (3, 1000000, 'Шприц', 5.0);
INSERT INTO "Goods" ("Code", "Count", "Name", "PriceRub")
VALUES (4, 1001, 'Плюмбус', 76.0);
INSERT INTO "Goods" ("Code", "Count", "Name", "PriceRub")
VALUES (5, 1001, 'Замок', 42000000.0);

SELECT setval(
    pg_get_serial_sequence('"Currencies"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Currencies") + 1,
        nextval(pg_get_serial_sequence('"Currencies"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Goods"', 'Code'),
    GREATEST(
        (SELECT MAX("Code") FROM "Goods") + 1,
        nextval(pg_get_serial_sequence('"Goods"', 'Code'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260614075709_InitialCreate', '10.0.4');

COMMIT;

